training:
  accumulate: 1
  batch_size: 32
  workers: 8
  eval_interval: 1
  final_epoch: 80
  last_no_mosaic: 0
  warm_up_steps: 1000
  using_autocast: True
  optimizer:
    lr: 0.005
    mode: default
    momentum: 0.937
    type: sgd
    warm_up_init_lr: 1e-05
    warm_up_init_momentum: 0.8
    weight_decay: 0.0005
  schedular:
    type: cosine
    extra: [{"lrf": 0.01}]
  train_img_anns_path: COCO/train2017_coco.json
  train_img_path: COCO/train2017
  val_img_anns_path: COCO/val2017_coco.json
  val_img_path: COCO/val2017
  val_metric: coco
