training:
  accumulate: 1
  batch_size: 8
  workers: 8
  eval_interval: 20
  final_epoch: 200
  last_no_mosaic: 20
  warm_up_steps: 1000
  using_autocast: True
  optimizer:
    lr: 0.025
    mode: default
    momentum: 0.937
    type: sgd
    warm_up_init_lr: 1e-05
    warm_up_init_momentum: 0.8
    weight_decay: 0.0005
  schedular:
    type: cosine
    extra: [{"lrf": 0.01}]
  train_img_anns_path: CityPerson/anno_train_coco_style.json
  train_img_path: CityPerson/train
  val_img_anns_path: CityPerson/anno_val_coco_style.json
  val_img_path: CityPerson/val
  val_metric: mr
