training:
  accumulate: 1
  batch_size: 16
  workers: 16
  eval_interval: 20
  final_epoch: 300
  last_no_mosaic: 0
  warm_up_steps: 500
  using_autocast: True
  optimizer:
    lr: 0.005
    mode: groups
    para_group: [{'backbone':{'lr':0.8, 'momentum':1.0},
                  'neck':{'lr':0.9, 'momentum':1.0},
                  'head':{'lr':0.25, 'momentum':1.0}}]
    momentum: 0.937
    type: sgd
    warm_up_init_lr: 1e-06
    warm_up_init_momentum: 0.5
    weight_decay: 0.0005
  schedular:
    type: cosine
    extra: [{"lrf": 0.01}]
  train_img_anns_path: CrowdHuman/annotation_train_coco_style.json
  train_img_path: CrowdHuman/Images_train
  val_img_anns_path: CrowdHuman/annotation_val_coco_style.json
  val_img_path: CrowdHuman/Images_val
  val_metric: coco
