exp_name: YOLOv3_step_finetune
inference:
  iou_thres: 0.6
  nms_type: nms
  obj_thres: 0.5
loss:
  cls_type: bce
  focal_alpha: 0.25
  focal_gamma: 2.0
  reg_type: ['giou', 'l1']
  use_focal: False
  weight: [5.0, 5.0, 0.3]
model:
  anchor_ratios: [2, 3]
  anchor_scales: [0.75, 1]
  assignment_iou_threshold: 0.5
  assignment_iou_type: iou
  assignment_type: default
  backbone: darknet53
  fpnlevels: [3, 4, 5]
  head: yolov3_head
  name: yolov3
  neck: yolov3_neck
  use_anchor: True
seed: None
training:
  accumulate: 1
  batch_size: 8
  eval_interval: 20
  final_epoch: 30
  last_no_mosaic: 2
  optimizer:
    lr: 0.001
    mode: none
    momentum: 0.937
    type: sgd
    warm_up_init_lr: 1e-05
    warm_up_init_momentum: 0.8
    weight_decay: 0.0005
  schedular:
    type: step
    extra: [{"milestones":[20],"ratio":0.1}]
  train_img_anns_path: CrowdHuman/annotation_train_coco_style.json
  train_img_path: CrowdHuman/Images_train
  using_autocast: True
  val_img_anns_path: CrowdHuman/annotation_val_coco_style.json
  val_img_path: CrowdHuman/Images_val
  val_metric: coco
  warm_up_steps: 0
  workers: 4
